import "./globals.css";
import SessionWrapper from "../components/SessionWrapper";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-gradient-to-br from-[#000] via-[#63e] to-[#000] min-h-screen">
        <SessionWrapper>
          {children}
        </SessionWrapper>
      </body>
    </html>
  );
}
